export const messages = (data: any) => {
  var language = data;
  if (data == "en") {
    var messages = {
      passwordDifferError: "Password Does not Matched",
      signupSuccessful: "Signup successfully",
      passwordUpdateSuccessful: "Password Updated Successfully",
      loginSuccessful: "Login successfully",
      logoutSuccessful: "Logged out successfully",
      invalidAddress: "Not a valid address",
      addressRequired: "At least one address required",
      mediaRequired: "At least one media required",
      adminWithSameEmail: "Admin with Email: {{email}}  already exists.",
      SameEmail: "{{email}} Id already exists.",
      engine_companyAlreadyExist:
        "Engine company with name:  {{name}}  already exists.",
      engine_modelAlreadyExist:
        "Engine model with name :  {{name}}  already exists.",
      catAlreadyExist: "Category with name :  {{catName}}  already exists.",
      catNotFound: "Category with this name not exists",
      catShortNameAlreadyExist:
        "Category with short name: {{catName}}  already exists.",
      subCatShortNameAlreadyExist:
        "Sub Category with short name: {{catName}}  already exists.",
      sub_subCatAlreadyExist:
        "Sub-Sub-Category with name: {{catName}}  already exists.",
      subCatAlreadyExist:
        "Sub Category with name: {{catName}}  already exists.",
      noSuchAccount: "No such account exists with this email.",
      WrongPassword: "Wrong Password Please fill Correct Password.",
      faqAlready: "FAQ with question: {{question}}  already exists.",
      maxLimit:
        "You uploaded maximum limit {{limit}} ! please remove old ones then upload ",
      invalidPickupAddress: "Not a valid pickup address.",
      invalidDeliveryAddress: "Not a valid delivery address.",
      accountAlreadyExist:
        "Account with given Phone number and Role already exists.",
      noSuchAccountExist: "No such account exists.",
      noAccountMatch:
        "Unfortunately, there is no account matching that information on our records.",
      invalidMongoId: "{{key}} must be a valid mongo ID",
      noDatafound: "No Record Found",
      nobusinessfoundId: "Business not found with this id : {{id}}",
      noDatafoundWith: "No Record Found with Email: {{email}}",
      noDatafoundWithID: "No Record Found With ID",
      alreadyExist: "Already Exists",
      userExist: "User already Exists",
      phoneNumberTaken: "Phone number already taken by some other user.",
      invalidAction: "Invalid action",
      unprocessableEntity: "Unprocessable entity",
      somethingwrong: "Something went wrong",
      bookingStatusError:
        "Status can't be changed from '{{old}}' state to '{{new}}' state.",
      accountBlocked:
        "Your account has been marked as InActive, Please contact to Admin",
      sessionExpired: "Session expired! Please login again.",
      noToken: "No token found",
      invalidToken: "Invalid token",
      unAuthRole: "Unauthorized role! Access denied",
      incorrectOldPass: "Please enter correct old password",
      accountUnverifiedAdmin:
        "Your Account is unverified, please contact Admin",
      success: "success",
      wrongoldPassword: "Wrong old Password",
      roomIdRequired: "RoomId is required",
      sendToRequired: "SendTo is required",
      businessIdRequired: "BusinessId is required",
      csvFileRequired: "Csv file is required",
      catRequired: "CategoryId is required",
      bothPassSame: "Old and New password can not be same",
      bothNewAndConfirmSame: "New password and Confirm password must be the same",
      userDelete: "Deleted Successfully",
      vehicleIdRequired: "VehicleId is required if type is vehicle",
      vehicleTypeRequired: "VehicleType is required if type is vehicle",
      ar_vehicleTypeRequired: "Ar_vehicleType is required if type is vehicle",
      vehicleSizeRequired: "VehicleSize is required if type is vehicle",
      ar_vehicleSizeRequired: "Ar_vehicleSize is required if type is vehicle",
      equipmentIdRequired: "EquipmentId is required if type is equipment",
      ar_equipmentNameRequired: "Ar_equipmentName is required if type is equipment",
      equipmentNameRequired: "EquipmentName is required if type is equipment",
      alreadyTakenAction: "Your booking already has been {{action}}",
      alreadyTakenAction_thisBooking: "You have already {{action}} this booking.",
      pickupAddressRequired: "Pickup address is required if type is vehicle",
      pickupCityRequired: "Pickup city is required if type is vehicle",
      pickupCountryRequired: "Pickup  country is required if type is vehicle",
      pickupStateRequired: "Pickup state is required if type is vehicle",
      pickupZipcodeRequired: "Pickup zipcode is required if type is vehicle",
      pickupLatRequired: "Pickup latitude is required if type is vehicle",
      pickupLongRequired: "Pickup longitude is required if type is vehicle",
      nofile_upload: 'No files were uploaded.',
      typeRequired: 'Type is required',
      invalidFile: 'Invalid file.',
      imageRequired: 'Image is required',
      invalidOtp: "Invalid Otp",
      sendOtp: "Otp send successfully",
      verifiedOtp: "Valid Otp",
      expiredOtp: "Otp has been expired.",
      un_valid_user: "Role should be [equipment_user, vehicle_user , vehicle_equipment ]",
      already_give_rating: "You have already provided a rating for this order.",
      maxEquipmentCount: "You have {{totalEquipments}} equipment available, but you selected addresses for {{selectedEquipment}}.",
      maxVehicleCount: "You have {{totalVehicles}} vehicle available, but you selected addresses for {{selectedVehicle}}.",
      faq_AlreadyExist:
        "faq with que :  {{que}}  already exists.",
      invalidPhoneNumberORcountryCode: "You have entered an invalid phoneNumber or countryCode",
      equipment_notAvailable: "No equipment available at this time",
      transport_notAvailable: "No transport available at this time",
      not_allowed_delete_equip_vehicle: "You cannot edit or delete this {{type}} while an order is in progress.",
      B2B: "This company exclusively engages in business-to-business (B2B) operations and does not cater to individual users.",
      notification_title: "Order Status Notification From Fliz Company",
      notification_description: "Hi {{userName}}, Your order OrderId: {{orderId}} has been {{bookingStatus}} ",
      notification_description_for_company: "Hi {{companyName}}, The order OrderId: {{orderId}} has been {{bookingStatus}} by user",
      unpaid_payment: "Payment for this order is still due.",
      unAvailableItem: "This {{type1}} is not available at this time",
      updatedVersion_available: "Updated app version available"
    };
    return messages;
  } else if (language == "ar") {
    var messages = {
      passwordDifferError: "Password Does not Matched",
      wrongoldPassword: "Wrong old Password",
      passwordUpdateSuccessful: "Password Updated Successfully",
      signupSuccessful: "Signup successfully",
      loginSuccessful: "Login successfully",
      logoutSuccessful: "Logged out successfully",
      invalidAddress: "Not a valid address",
      addressRequired: "At least one address required",
      mediaRequired: "At least one media required",
      adminWithSameEmail: "Admin with Email: {{email}}  already exists.",
      SameEmail: "{{email}} Id already exists.",
      engine_companyAlreadyExist:
        "Engine company with name :  {{name}}  already exists.",
      engine_modelAlreadyExist:
        "Engine model with name :  {{name}}  already exists.",
      catAlreadyExist: "Category with name: {{catName}}  already exists.",
      catNotFound: "Category with this name not exists",
      catShortNameAlreadyExist:
        "Category with short name: {{catName}}  already exists.",
      subCatShortNameAlreadyExist:
        "Sub Category with short name: {{catName}}  already exists.",
      subCatAlreadyExist:
        "Sub Category with name: {{catName}}  already exists.",
      sub_subCatAlreadyExist:
        "Sub-Sub-Category with name: {{catName}}  already exists.",
      noSuchAccount: "No such account exists with this email.",
      WrongPassword: "Wrong Password Please fill Correct Password.",
      faqAlready: "FAQ with question: {{question}}  already exists.",
      maxLimit:
        "You uploaded maximum limit {{limit}} ! please remove old ones then upload ",
      invalidPickupAddress: "Not a valid pickup address.",
      invalidDeliveryAddress: "Not a valid delivery address.",
      accountAlreadyExist:
        "Account with given Phone number and Role already exists.",
      noSuchAccountExist: "No such account exists.",
      noAccountMatch:
        "Unfortunately, there is no account matching that information on our records.",
      invalidMongoId: "{{key}} must be a valid mongo ID",
      noDatafound: "No Record Found",
      nobusinessfoundId: "Business not found with this id: {{id}}",
      noDatafoundWith: "No Record Found with Email: {{email}}",
      noDatafoundWithID: "No Record Found With ID",
      alreadyExist: "Already Exists",
      userExist: "User already Exists",
      phoneNumberTaken: "Phone number already taken by some other user.",
      invalidAction: "Invalid action",
      unprocessableEntity: "Unprocessable entity",
      somethingwrong: "Something went wrong",
      bookingStatusError:
        "Status can't be changed from '{{old}}' state to '{{new}}' state.",
      accountBlocked:
        "Your account has been marked as InActive, Please contact to Admin",
      sessionExpired: "Session expired! Please login again.",
      noToken: "No token found",
      invalidToken: "Invalid token",
      unAuthRole: "Unauthorized role! Access denied",
      incorrectOldPass: "Please enter correct old password",
      accountUnverifiedAdmin:
        "Your Account is unverified, please contact Admin",
      success: "success",
      roomIdRequired: "RoomId is required",
      sendToRequired: "SendTo is required",
      businessIdRequired: "BusinessId is required",
      csvFileRequired: "Csv file is required",
      catRequired: "CategoryId is required",
      bothPassSame: "Old and New password can not be same",
      bothNewAndConfirmSame:
        "New password and Confirm password must be the same",
      userDelete: "Deleted Successfully",
      vehicleIdRequired: "vehicleId is required if type is vehicle",
      vehicleTypeRequired: "vehicleType is required if type is vehicle",
      ar_vehicleTypeRequired: "ar_vehicleType is required if type is vehicle",
      vehicleSizeRequired: "vehicleSize is required if type is vehicle",
      ar_vehicleSizeRequired: "ar_vehicleSize is required if type is vehicle",
      equipmentIdRequired: "EquipmentId is required if type is equipment",
      ar_equipmentNameRequired: "Ar_equipmentName is required if type is equipment",
      equipmentNameRequired: "EquipmentName is required if type is equipment",
      alreadyTakenAction: "Your booking already has been {{action}}",
      alreadyTakenAction_thisBooking: "You have already {{action}} this booking.",
      pickupAddressRequired: "Pickup address is required if type is vehicle",
      pickupCityRequired: "Pickup city is required if type is vehicle",
      pickupCountryRequired: "Pickup  country is required if type is vehicle",
      pickupStateRequired: "Pickup state is required if type is vehicle",
      pickupZipcodeRequired: "Pickup zipcode is required if type is vehicle",
      pickupLatRequired: "Pickup latitude is required if type is vehicle",
      pickupLongRequired: "Pickup longitude is required if type is vehicle",
      nofile_upload: 'No files were uploaded.',
      typeRequired: 'Type is required',
      invalidFile: 'Invalid file.',
      imageRequired: 'Image is required',
      invalidOtp: "Invalid Otp",
      sendOtp: "Otp send successfully",
      verifiedOtp: "Valid Otp",
      expiredOtp: "Otp has been expired.",
      un_valid_user: "Role should be [equipment_user, vehicle_user , vehicle_equipment ]",
      already_give_rating: "You have already provided a rating for this order.",
      maxEquipmentCount: "You have {{totalEquipments}} equipment available, but you selected addresses for {{selectedEquipment}}.",
      maxVehicleCount: "You have {{totalVehicles}} vehicle available, but you selected addresses for {{selectedVehicle}}.",
      faq_AlreadyExist:
        "faq with que :  {{que}}  already exists.",
      invalidPhoneNumberORcountryCode: "You have entered an invalid phoneNumber or countryCode",
      equipment_notAvailable: "No equipment available at this time",
      transport_notAvailable: "No transport available at this time",
      not_allowed_delete_equip_vehicle: "You cannot edit or delete this {{type}} while an order is in progress.",
      B2B: "This company exclusively engages in business-to-business (B2B) operations and does not cater to individual users.",
      notification_title: "Order Status Notification From Fliz Company",
      notification_description: "Hi {{userName}}, Your order OrderId: {{orderId}} has been {{bookingStatus}} ",
      notification_description_for_company: "Hi {{companyName}}, The order OrderId: {{orderId}} has been {{bookingStatus}} by user",
      unpaid_payment: "Payment for this order is still due.",
      unAvailableItem: "This {{type1}} is not available at this time",
      updatedVersion_available: "Updated app version available"
    };
    return messages;
  } else {
    var messages = {
      passwordDifferError: "Password Does not Matched",
      wrongoldPassword: "Wrong old Password",
      passwordUpdateSuccessful: "Password Updated Successfully",
      signupSuccessful: "Signup successfully",
      loginSuccessful: "Login successfully",
      logoutSuccessful: "Logged out successfully",
      invalidAddress: "Not a valid address",
      addressRequired: "At least one address required",
      mediaRequired: "At least one media required",
      adminWithSameEmail: "Admin with Email: {{email}}  already exists.",
      SameEmail: "{{email}} Id already exists.",
      engine_companyAlreadyExist:
        "Engine company with name :  {{name}}  already exists.",
      engine_modelAlreadyExist:
        "Engine model with name :  {{name}}  already exists.",
      catAlreadyExist: "Category with name:  {{catName}}  already exists.",
      catNotFound: "Category with this name not exists",
      catShortNameAlreadyExist:
        "Category with short name: {{catName}}  already exists.",
      subCatShortNameAlreadyExist:
        "Sub Category with short name: {{catName}} already exists.",
      subCatAlreadyExist: "Sub Category with name: {{catName}} already exists.",
      sub_subCatAlreadyExist:
        "Sub-Sub-Category with name: {{catName}}  already exists.",
      noSuchAccount: "No such account exists with this email.",
      WrongPassword: "Wrong Password Please fill Correct Password.",
      faqAlready: "FAQ with question: {{question}}  already exists.",
      maxLimit:
        "You uploaded maximum limit {{limit}} ! please remove old ones then upload ",
      invalidPickupAddress: "Not a valid pickup address.",
      invalidDeliveryAddress: "Not a valid delivery address.",
      accountAlreadyExist:
        "Account with given Phone number and Role already exists.",
      noSuchAccountExist: "No such account exists.",
      noAccountMatch:
        "Unfortunately, there is no account matching that information on our records.",
      invalidMongoId: "{{key}} must be a valid mongo ID",
      noDatafound: "No Record Found",
      nobusinessfoundId: "Business not found with this id: {{id}}",
      noDatafoundWith: "No Record Found with Email: {{email}}",
      noDatafoundWithID: "No Record Found With ID",
      alreadyExist: "Already Exists",
      userExist: "User already Exists",
      phoneNumberTaken: "Phone number already taken by some other user.",
      invalidAction: "Invalid action",
      unprocessableEntity: "Unprocessable entity",
      somethingwrong: "Something went wrong",
      bookingStatusError:
        "Status can't be changed from '{{old}}' state to '{{new}}' state.",
      accountBlocked:
        "Your account has been marked as InActive, Please contact to Admin",
      sessionExpired: "Session expired! Please login again.",
      noToken: "No token found",
      invalidToken: "Invalid token",
      unAuthRole: "Unauthorized role! Access denied",
      incorrectOldPass: "Please enter correct old password",
      accountUnverifiedAdmin:
        "Your Account is unverified, please contact Admin",
      success: "success",
      roomIdRequired: "RoomId is required",
      sendToRequired: "SendTo is required",
      businessIdRequired: "BusinessId is required",
      csvFileRequired: "Csv file is required",
      catRequired: "CategoryId is required",
      bothPassSame: "Old and New password can not be same",
      bothNewAndConfirmSame:
        "New password and Confirm password must be the same",
      userDelete: "Deleted Successfully",
      vehicleIdRequired: "vehicleId is required if type is vehicle",
      vehicleTypeRequired: "vehicleType is required if type is vehicle",
      ar_vehicleTypeRequired: "ar_vehicleType is required if type is vehicle",
      vehicleSizeRequired: "vehicleSize is required if type is vehicle",
      ar_vehicleSizeRequired: "ar_vehicleSize is required if type is vehicle",
      equipmentIdRequired: "EquipmentId is required if type is equipment",
      ar_equipmentNameRequired: "Ar_equipmentName is required if type is equipment",
      equipmentNameRequired: "EquipmentName is required if type is equipment",
      alreadyTakenAction: "Your booking already has been {{action}}",
      alreadyTakenAction_thisBooking: "You have already {{action}} this booking.",
      pickupAddressRequired: "Pickup address is required if type is vehicle",
      pickupCityRequired: "Pickup city is required if type is vehicle",
      pickupCountryRequired: "Pickup  country is required if type is vehicle",
      pickupStateRequired: "Pickup state is required if type is vehicle",
      pickupZipcodeRequired: "Pickup zipcode is required if type is vehicle",
      pickupLatRequired: "Pickup latitude is required if type is vehicle",
      pickupLongRequired: "Pickup longitude is required if type is vehicle",
      nofile_upload: 'No files were uploaded.',
      typeRequired: 'Type is required',
      invalidFile: 'Invalid file.',
      imageRequired: 'Image is required',
      invalidOtp: "Invalid Otp",
      sendOtp: "Otp send successfully",
      verifiedOtp: "Valid Otp",
      expiredOtp: "Otp has been expired.",
      un_valid_user: "Role should be [equipment_user, vehicle_user , vehicle_equipment ]",
      already_give_rating: "You have already provided a rating for this order.",
      maxEquipmentCount: "You have {{totalEquipments}} equipment available, but you selected addresses for {{selectedEquipment}}.",
      maxVehicleCount: "You have {{totalVehicles}} vehicle available, but you selected addresses for {{selectedVehicle}}.",
      faq_AlreadyExist:
        "faq with que :  {{que}}  already exists.",
      invalidPhoneNumberORcountryCode: "You have entered an invalid phoneNumber or countryCode",
      equipment_notAvailable: "No equipment available at this time",
      transport_notAvailable: "No transport available at this time",
      not_allowed_delete_equip_vehicle: "You cannot edit or delete this {{type}} while an order is in progress.",
      B2B: "This company exclusively engages in business-to-business (B2B) operations and does not cater to individual users.",
      notification_title: "Order Status Notification From Fliz Company",
      notification_description: "Hi {{userName}}, Your order OrderId: {{orderId}} has been {{bookingStatus}}",
      notification_description_for_company: "Hi {{companyName}}, The order OrderId: {{orderId}} has been {{bookingStatus}} by user",
      unpaid_payment: "Payment for this order is still due.",
      unAvailableItem: "This {{type1}} is not available at this time",
      updatedVersion_available: "Updated app version available"
    };
    return messages;
  }
};
